[global]
disableWatchdogWarning = false
showWarningOnDirectExecution = true
dataFrameSerialization = "arrow"

[logger]
level = "info"
messageFormat = "%(asctime)s.%(msecs)03d %(message)s"

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = false
enforceSerializableSessionState = false

[server]
folderWatchBlacklist = []
fileWatcherType = "auto"
headless = true
runOnSave = false
port = 8080
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = false
enableStaticServing = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8080

[deprecation]
showfileUploaderEncoding = true
showPyplotGlobalUse = true


[theme]
base="light"
primaryColor="#8210d8"
secondaryBackgroundColor="#ededed"
textColor="#111111"
